### ISSUE TITLE
Galaxy Version

### ISSUE THREAD

**Issue by SpontaneousDuck** [kevincoakley/ansible-role-anaconda#2]
The newest release was never pushed to Galaxy. Not sure why... Thanks for the work by the way!

**Comment by kevincoakley** [comment]
Galaxy is very picky about the version number given to releases, I guess it didn't like 2019.07.00. Let me see if I have time later today to update the role and push out a newer version.

**Comment by SpontaneousDuck** [comment]
Thanks @kevincoakley !

**Comment by kevincoakley** [comment]
Version 6.0.0 should be available at https://galaxy.ansible.com/kevincoakley/anaconda/ . Let me know if you have any issues.

**Comment by SpontaneousDuck** [comment]
Looks great! Thank you!
